import Head from "next/head";
import { useTranslation } from "next-i18next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import { Box } from "@mui/system";

export default function Home() {
  const { t } = useTranslation("common");
  return (
    <div>
      <Head>
        <title>Algerian Tech Makers </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        sx={{
          backgroundColor: "blue",
        }}
      >
        {t(`hello`)}
      </Box>
    </div>
  );
}
export const getServerSideProps = async ({ locale }) => ({
  props: {
    ...(await serverSideTranslations(locale, ["common"])),
  },
});
